name: GitHub-Profile-Summary-Cards
on:
  schedule: # Run automatically every 24 hours
    - cron: "0 18 * * *"
  workflow_dispatch: # Allow manual run
  push: {branches: ["master", "main"]}

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3
      
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          # We can use the same token you created before
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          # This automatically generates files in your repo
