name: Metrics
on:
  # Schedule daily updates (00:00 IST roughly)
  schedule: [{cron: "30 18 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing to master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: dineshingale
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          
          # Output file name
          filename: github-metrics.svg
          
          # Theme (Your preference)
          theme: tokyonight
          
          # Plugins
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_streak: yes
          plugin_streak_mode: weekly
