name: Metrics
on:
  # Schedule daily updates (00:00 IST)
  schedule: [{cron: "30 18 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # --- General Settings ---
          user: dineshingale
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          filename: github-metrics.svg
          theme: tokyonight
          
          # --- 1. The "Activity Graph" (Wave style) ---
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          
          # --- 2. The "Streak" Stats ---
          plugin_streak: yes
          
          # --- 3. The "Trophies" (Achievements) ---
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          
          # --- 4. The "Top Languages" ---
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 8
